stages:
- stage:
  displayName: 'Generate translated'

  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
        addToPath: true

    - script: |
        echo "Installing dependencies"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        git clone https://$(TARGET_WIKI_PAT)@$(TARGET_WIKI_DOMAIN_URL)

    # - script: |
    #     python main.py
    #   displayName: 'Run script'
    #   env:
    #     AZURE_OPENAI_API_KEY: $(AZURE_OPENAI_API_KEY)  # secret variable

    - script: |
        mkdir -p Translated
        echo "This is a test file." > Translated/test.txt
      displayName: 'Create test.txt in Translated folder'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'Translated'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/translated.zip'
        replaceExistingArchive: true
        
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'output'
        publishLocation: 'pipeline'

